### ISSUE TITLE
Running `grunt static` gives me no local env

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#10]
Unfortunately, following the instructions in the README gives me no joy. When I visit http://localhost:5000/ after running `grunt static` I just get "This webpage is not available: ERR_ADDRESS_UNREACHABLE" in Chrome.

Any suggestions? The task runs without errors:

> $ grunt static
  Running "env:dev" (env) task
  Running "shell:run" (shell) task
  [Wed Jul 08 2015 10:04:52 GMT+0800 (MYT)] INFO Connecting...
  Node app is running on port 5000
  Done, without errors.

**Comment by jonlay** [comment]
The conclusion from our pairing was that this isn't doable for now, because you need Foreman running in order to get a local version of the app working.

**Comment by marcelkalveram** [comment]
Yep unfortunately, because it has to read the Slack parameters from your local env file and that doesn't happen when running ```grunt static```

**Comment by marcelkalveram** [comment]
I've removed `grunt static` from the gruntfile as it isn't needed anymore. We use `foreman start web` instead.
