### ISSUE TITLE
User feedback should be posted into a channel, not pinged to all users

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#12]
This is currently causing some issues for us because users get repeatedly pinged by Oskar in 1:1 chats when someone else provides feedback, including when we submit our own feedback.

To resolve this, Oskar should drop all feedback into a group/channel instead of via 1:1.

At Hanno, we use #chico, but I know other teams use something different. So this target channel should be defined in Oskar's app settings, and the default (#general) should be set in the default app.json config, so that it's simple for users to get going with.

This would also solve issue #3

**Comment by marcelkalveram** [comment]
Stuff is now going into the channel with the ID of environment variable CHANNEL_ID. If this is not defined it pings each user separately as before.

**Comment by jonlay** [comment]
Awesome :+1:  Could we document this in the README so that other people can understand how to set it up?

**Comment by marcelkalveram** [comment]
Working now. Added instructions for CHANNEL_ID to the readme
