### ISSUE TITLE
Marketing content should be on a separate GitHub pages account

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#20]
Currently, our repository includes all marketing content on the app homepage, and requires users to go to /dashboard to view the stats and metrics.

This doesn't make a great deal of sense for users running the app for themselves (they don't want an Oskar marketing site) and also makes it harder to build and test the app.

Proposed changes:

1. Move all marketing content to a `gh-pages` branch
2. Remove the /dashboard page and move all of this to the application main view
3. Point oskar.hanno.co at the GitHub Pages URL, and move Hanno's internal Oskar install away from oskar.hanno.co/dashboard, to break apart any marketing content from Hanno's internal Oskar installation.

I'll do a little work on the static side side of things here, and ping you here @marcelkalveram when I'm done with things, so you can merge things into master.

**Comment by marcelkalveram** [comment]
Sounds like a good idea. Agree with everything you're saying.

**Comment by jonlay** [comment]
@marcelkalveram: I’ve removed `/dashboard` and moved it all to `/`. That’s on a branch called `nomarketing`.

I’ve also moved all the marketing stuff onto a `gh-pages` branch and that works okay. When I point oskar.hanno.co to this URL, it should work fine: http://wearehanno.github.io/oskar/

To deploy this, you’d need to:

1) Test the `nomarketing` branch. I can’t do `npm install` at the moment because of an issue with the time package, so I haven’t properly checked this.
2) Maybe update the tests
3) Tell me that it’s okay, and you’re ready.
4) Then I will update the DNS for oskar.hanno.co to point at the gh-pages setup
5) You’ll need to update the internal URL for our Oskar app to something like jazz.hanno.co, perhaps (since oskar.hanno.co will just be a marketing site now).
6) Then, we can merge nomarketing => master and deploy the new dashboardless design for public use, and to update Hanno’s own Oskar install.

**Comment by jonlay** [comment]
I've updated the DNS for oskar.hanno.co to point at gh-pages, and set up the new internal Hanno URL for our own Oskar account. Over to you, for the branch merging and marketing removal!

**Comment by marcelkalveram** [comment]
Done. I've merge the `nomarketing` branch, reinstalled the npm modules without any issues and tests are passing as well.

**Comment by jonlay** [comment]
Awesome! Thanks a ton.
