### ISSUE TITLE
Remove /target from the repository

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#21]
It's quite undesirable for the app to include a `target` directory containing compiled files. Wherever possible, we should figure out how to get Heroku to do this themselves via a buildpack or something. It shouldn't be terribly hard to run the `grunt prepublish` on deployment.

**Comment by marcelkalveram** [comment]
I've tried this in the past but the (inofficial) CoffeeScript buildpack didn't work.

This is the commit where I removed the buildpack instructions https://github.com/wearehanno/oskar/commit/9483edf4ebdab2c4f2d0a632004160ee833e6e33

**Comment by marcelkalveram** [comment]
I've removed the target folder and I'm now running the coffee file directly. Here's how I did it:
http://stackoverflow.com/questions/6356267/can-i-run-coffeescript-in-heroku

**Comment by jonlay** [comment]
Brilliant, although I'm pretty sure the `/target` folder is still there :wink: 

https://github.com/wearehanno/oskar/tree/master/target

**Comment by marcelkalveram** [comment]
Weird, I had removed it before, but I think it got added again after merging it with the `nomarketing`branch. Anyway, it's gone now :+1:

**Comment by jonlay** [comment]
Fantastic. Do we still need to do `grunt prepublish` while working locally, as the README says? https://github.com/wearehanno/oskar/blob/master/README.md#local-environment-quickstart

**Comment by marcelkalveram** [comment]
I've just removed grunt as it's not needed anymore.
