### ISSUE TITLE
Remove the dependency on Heroku to test

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#24]
Right now, we are depending on Foreman to get the app running locally.

But Foreman has been discontinued: https://devcenter.heroku.com/changelog-items/692

2 steps:

1. Switch from Foreman, to Heroku Local (short-term)
2. Eventually, make sure we can run the app locally (like any other Node app) without having to use Heroku at all. Maybe using something like [nodemon](https://github.com/remy/nodemon)

**Comment by marcelkalveram** [comment]
I guess the only reason we're depending on foreman is because we're using the `.env` file to define environment variables. In theory we could already move away from foreman by only using the config files in the `config` directory.

**Comment by jonlay** [comment]
Hmm, that's interesting. I thought there were some other reasons and that Foreman was doing something more complex.

Perhaps I'm wrong, and Heroku Local is a sensible way to do things--the `procfile` coffeescript thing was a good example of how the local app can be better tested for Heroku by using this technique, I guess.

**Comment by marcelkalveram** [comment]
Yeah, as mentioned in the readme you can just use the file ```config/local.json``` to configure Oskar, and then run ```node_modules/.bin/coffee src/index.coffee``` instead of foreman/forego.

I also just updated to Heroku Local locally by running ```heroku local``` and it does everything automatically, so no need to change anything in the repository here.
