### ISSUE TITLE
Oskar should be more vocal about asking people for a feedback message

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#28]
Right now, he congratulates them (which is nice!) but doesn't really ask for more information. It'd be sensible to make this request a bit more visible, and clean up the messaging a bit more here.

**Comment by marcelkalveram** [comment]
I don't really understand which part of the messaging you're refering to? If you're talking about the onboarding process, then that's because Oskar doesn't currently support a feedback message after submitting a number. Did you mean we should include that?

**Comment by jonlay** [comment]
![screen shot 2015-12-28 at 09 48 24](https://cloud.githubusercontent.com/assets/1898889/12013040/2ccc0d68-ad48-11e5-8c41-29bd099c1ab4.png)

It's just that the "Wanna tell me why things are going so well?" is easy to miss, and in some messages, is even less clear. I'd side with making it more of a request, than an optional thing:

"Why not type a message to let your team know why things are going so well"

And to have this in bold?

**Comment by marcelkalveram** [comment]
Resolved in my latest commit 7fc520a
