### ISSUE TITLE
Status messages chopped off if apostrophe present

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#29]
Filed a status as follows:

> 4: Having a very nice blended smoothie at the moment, thanks Jazz. Not sure you’d like it that much though.

It was then output to our Slack firehose as:

![2015-11-10 04 34 19 pm](https://cloud.githubusercontent.com/assets/1898889/11057790/fb94911a-87c8-11e5-8eda-08b5bdf92732.png)

Not yet sure if this only happens when you try to report a status as `5: Status here` or whether it will happen if you try and submit the rating and the message separately. Will see if I can try that next time and clarify,

**Comment by jonlay** [comment]
Can confirm that apostrophes only chop off the input text if you're doing an inline status submission (trying to submit a number and a status at the same time)

**Comment by marcelkalveram** [comment]
I've modified the regex so that it allows for apostrophes as well.
