### ISSUE TITLE
Oskar pings me with updates from my teammates when I am offline

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#3]
This is a bad thing because it clutters up my inbox.

I would suggest either:

- Send all of these "Bob just checked in" notifications to a regular Slack channel like #general
- Group all of these updates, and only send them to me when I come back online.

I don't have a strong preference :smile:

**Comment by jonlay** [comment]
Let's make this one a high-priority fix, because i think it's driving everyone a bit mad :stuck_out_tongue:

**Comment by marcelkalveram** [comment]
Commit b6554fe49d6a044b3d5a457a50ad3a9e7ee36c76 should resolve this.

**Comment by jonlay** [comment]
Alright. Hopefully this won't exclude the feedback from appearing in the general channel if you work on #12 :smile:

**Comment by marcelkalveram** [comment]
Has been fixed thanks to #12
