### ISSUE TITLE
Oskar is introducing itself everyday

### ISSUE THREAD

**Issue by geoffdlbl** [wearehanno/oskar#33]
Oskar keeps introducing itself everyday (sometimes multiple times a day) instead of doing it only on first use. 
Running on a free Heroku account (kept alive and shutdown during the night).

<img width="563" alt="screen shot 2015-11-20 at 09 10 41" src="https://cloud.githubusercontent.com/assets/1092236/11294831/d2e8e72a-8f66-11e5-8611-dd7f44370887.png">

**Comment by marcelkalveram** [comment]
Hey there, I've tried to reproduce the issue and fixed a couple of things in the onboardingHelper that might have caused a problem where Oskar looks for the onboarding status even though it hasn't been retrieved from the persistent data store.

By the way: in one of your cases above it seems you didn't complete the onboarding process. It's only complete after you've answered with a status from 1 to 5.

Could you do me favour and test again if you find the time? I've also included a log entry in the onboardingHelper saying ```save onboarding for user #{userId}: #{status}```. If you look into your Heroku logs, you should see the ```status``` that it takes from the database. If it's not 3 after you've completed the onboarding process, there must be another problem.

Thanks a lot for your patience and cooperation!

**Comment by geoffdlbl** [comment]
Hi.
We have installed the last version and it seems solved. The log indicates a 3 status on boarding for all users.
In the same time we upgraded to a paid Heroku and maybe it helped to solve the issue (previously we had a free one we kept alive except during night).

**Comment by marcelkalveram** [comment]
Thanks for the feedback and sorry for not getting back to you sooner. I'll close this issue then.
