### ISSUE TITLE
Lots of duplicated JS files

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#6]
Hey @marcelkalveram 

I notice there are a bunch of duplicate JS and .coffee files in the repo. Example: https://github.com/wearehanno/oskar/blob/master/src/index.js

1. Can all of them be stripped out, perhaps?
2. If they're needed for Heroku, is there a way to do a build step to compile them, rather than keeping them in the repo?
3. Or could this be documented in the README at least, so it's easier to see how to contribute?

All in the name of a happier, cleaner Oskar :laughing:

**Comment by jonlay** [comment]
Hey @marcelkalveram any chance you could help me understand this? Perhaps I can help with cleanup in the meantime :smile:

**Comment by jonlay** [comment]
I notice that there's also a [Coffeescript Buildpack for Heroku](https://github.com/aergonaut/heroku-buildpack-coffeescript) which might be a solution.

**Comment by marcelkalveram** [comment]
Resolved this with the latest commit 9f0724f
