### ISSUE TITLE
Oskar just said "H"

### ISSUE THREAD

**Issue by lailavon** [wearehanno/oskar#7]
<img width="576" alt="screen shot 2015-07-07 at 09 12 07" src="https://cloud.githubusercontent.com/assets/10697519/8540842/9b33aab0-2489-11e5-86f2-6eba18b4bc8b.png">
Didn't even ask me how I was doing today.. :(

**Comment by jonlay** [comment]
![hfromsteps](https://cloud.githubusercontent.com/assets/1898889/8540870/16c39a1e-24bc-11e5-874a-d3c53a9b2955.jpg)

**Comment by marcelkalveram** [comment]
Restarted him, should be fixed now.

**Comment by jonlay** [comment]
Yeah, I can confirm that this is now resolved.
