### ISSUE TITLE
Feature request: allow me to submit feedback with [rating]: [message]

### ISSUE THREAD

**Issue by jonlay** [wearehanno/oskar#9]
Hey!

Since we all use Oskar lots, we know that when we tell him our 1/5 rating of how we feel, he's going to follow up asking for a little more info.

Would it be possible to optionally submit both values at once? i.e.

Old:

> Oskar: Tell me how you feel, from 1-5
> Jon: 4
> Oskar: Great, please tell me more
> Jon: Blah blah blah ready to have a good day

Proposed:

> Oskar: Tell me how you feel, from 1-5
> Jon: 4: Blah blah blah ready to have a good day

**Comment by marcelkalveram** [comment]
Implemented this today. Please give it a try next time you submit your status.

**Comment by jonlay** [comment]
Unfortunately, this doesn't seem to work. Can you confirm that it's working on our internal deployed version of Oskar?

![2015-08-19 11 01 50 am](https://cloud.githubusercontent.com/assets/1898889/9353654/e12adb20-4661-11e5-99bb-31361745d4ec.png)

**Comment by marcelkalveram** [comment]
I've just tested this and it seems to work. It probably didn't understand dots, commas and dashes which is why I just added them to the regex (https://github.com/wearehanno/oskar/commit/9ce67b6a3b20642507215b3602a2361d7415306c).

**Comment by jonlay** [comment]
Ah, perfect. I'll give that a go once he restarts!
